version: '3.7'
services:
  web-app:
    build:
      context: ./Web.Api1/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  react-app:
    build: 
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - 3001:3000